<a href="https://colab.research.google.com/github/meDOBBY21/MDSC-102/blob/main/204217-MDSC102-Assignment2(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**numpy - Basics Notebook**

---



Importing numpy and creating an alias 'np' to make the numpy access easier

In [93]:
import numpy as np

a=np.array([1,2,2])

a


array([1, 2, 2])

#Shape
It will the shape of the array


*   It will give inside array size if all inside arrays are of same size.





In [94]:
a.shape

(3,)

In [95]:
b=np.array([[1,2],[4]])

b.shape

<ipython-input-95-4f52e098b5af>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([[1,2],[4]])


(2,)

In [96]:
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])

c.shape

(2, 2, 3)

#Dimension
It will give what Dimension the array is in.

For a n-dim array with different shapes,it considers inside arrays as single element.
The reason we got 1

In [97]:
b.ndim

1

c is a 3-dim array as respective dimensions have equal number of elements.

In [98]:
c.ndim

3

Creating n-dim array

In [99]:
np.array([1,2],ndmin=5)

array([[[[[1, 2]]]]])

#Accessing elemnts in n-dim array

With index

In [100]:
shape=c.shape

for i in range(shape[0]):
    for j in range(shape[1]):
        for k in range(shape[2]):
            print(c[i,j,k],end=" ")
        print()
    print("--------")




1 2 3 
4 5 6 
--------
7 8 9 
0 1 2 
--------


Without index

In [101]:
for rect in c:
    for row in rect:
        for ele in row:
            print(ele,end=" ")
        print()
    print("---------")

1 2 3 
4 5 6 
---------
7 8 9 
0 1 2 
---------


#dtype

Cretating an array with specific datatype

Creating complex numbers

In [102]:
np.array([1,2,-4],dtype=complex)

array([ 1.+0.j,  2.+0.j, -4.+0.j])

Creating str type

In [103]:
np.array([1,2],dtype=str)

array(['1', '2'], dtype='<U1')

#Zeros array

Creates an array with given dimensions keeping each element as 0

In [104]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# Empty array (Random array)

Creates an array with given dimensions keeping each element with random value.

**NOTE**:By default its float

In [105]:
a=np.empty((2,3))

**Like**

ones_like : creates a array given a array with replacing elements with 1




In [106]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

zeroes_like : creates a array given a array with replacing elements with 0

In [107]:
np.zeros_like(a)

array([[0., 0., 0.],
       [0., 0., 0.]])

#Linspace

Creates a series of specified number of numbers with given strat and end points.

In [108]:
np.linspace(2,20,6)

array([ 2. ,  5.6,  9.2, 12.8, 16.4, 20. ])

we can also reshape in which ever shape we want

In [109]:
np.linspace(2,20,6).reshape(2,3)

array([[ 2. ,  5.6,  9.2],
       [12.8, 16.4, 20. ]])

#**MATRIX**

Creating a matrix

NOTE: use ' ( ' not  ' [ '

In [110]:
mat=np.array(((2,3),(3,2)))
mat

array([[2, 3],
       [3, 2]])

Multiplication

In [111]:
b=np.array(((1,0),(0,1)))
np.matmul(mat,b)

array([[2, 3],
       [3, 2]])

Dot product

In [112]:
np.dot(mat,b)

array([[2, 3],
       [3, 2]])

#Flatten and Ravel

flatten creates a copy

ravel creates a view

In [113]:
a=mat.flatten()
a

array([2, 3, 3, 2])

In [114]:
mat.ravel()

array([2, 3, 3, 2])

Indexing and Slicing

In [115]:
a=np.linspace(1,100,15,dtype=int)
a

array([  1,   8,  15,  22,  29,  36,  43,  50,  57,  64,  71,  78,  85,
        92, 100])

In [116]:
a[1:10:3]

array([ 8, 29, 50])

In [117]:
a[2::2]

array([ 15,  29,  43,  57,  71,  85, 100])

In [118]:
a[::-5]

array([100,  64,  29])

In [119]:
a=a.reshape(3,5)
a

array([[  1,   8,  15,  22,  29],
       [ 36,  43,  50,  57,  64],
       [ 71,  78,  85,  92, 100]])

In [120]:
a[1:2:]

array([[36, 43, 50, 57, 64]])

In [121]:
a[::-1]

array([[ 71,  78,  85,  92, 100],
       [ 36,  43,  50,  57,  64],
       [  1,   8,  15,  22,  29]])

#**MAX and MIN**

argmin - gives the index of the min element after flattening.

argmax -  gives the index of the max element after flattening.

In [122]:
np.argmax(a)

14

In [123]:
np.argmin(a)

0

max gives the max element in the array.

min gives the min element in the array.

In [124]:
a.max()

100

max can also give maxima in each coloumn and row

In [125]:
print(a.max(axis=1))
print(a.max(axis=0))

[ 29  64 100]
[ 71  78  85  92 100]


#**Sorting**

In [126]:
b=np.array([4,1,8,-2,41])
b.sort()
b

array([-2,  1,  4,  8, 41])

Sorting elements along row

In [127]:
a.sort()
a

array([[  1,   8,  15,  22,  29],
       [ 36,  43,  50,  57,  64],
       [ 71,  78,  85,  92, 100]])

Sorting can be done along coumn also

In [128]:
a.sort(axis=0)
a

array([[  1,   8,  15,  22,  29],
       [ 36,  43,  50,  57,  64],
       [ 71,  78,  85,  92, 100]])

#**Maxima and Minina**

In [130]:
a=np.sqrt(np.linspace(-2,2,4))

<ipython-input-130-59402d73a37e>:1: RuntimeWarning: invalid value encountered in sqrt
  a=np.sqrt(np.linspace(-2,2,4))


nanmx will find max among the numbers leaving nan vlaues

In [131]:
np.nanmax(a)

1.4142135623730951

#**Percentile**


It is used to compute the value at a given percentile in an array.

In [133]:
a=np.array([[0,.6,1.2],[1.8,2.4,3.0]])
a

array([[0. , 0.6, 1.2],
       [1.8, 2.4, 3. ]])

In [137]:
np.percentile(a,100)

2.25